version: "3"
services:
  db:
    image: ghcr.io/akdasa-studios/shlokas-db:latest
    restart: always
    expose:
      - 5984
    env_file:
      - environment.e2e.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 10s
      timeout: 10s
      retries: 5

  auth:
    image: ghcr.io/akdasa-studios/shlokas-auth:latest
    restart: always
    expose:
      - 3000
    env_file:
      - environment.e2e.env
    depends_on:
      db:
        condition: service_healthy

  mail:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    expose:
      - "1025"
    ports:
      - "1080:1080"
      - "1025:1025"

  landing:
    image: ghcr.io/akdasa-studios/shlokas-landing:latest
    expose:
      - 80

  content:
    image: ghcr.io/akdasa-studios/shlokas-landing:latest
    # image: shlokas-content-content:latest
    restart: always
    expose:
      - 80
    volumes:
      - ./content:/usr/share/nginx/html

  balancer:
    image: ghcr.io/akdasa-studios/shlokas-balancer:latest
    # image: shlokas-balancer-balancer:latest
    ports:
      - 80:80
      - 443:443
    env_file:
      - environment.e2e.env
    depends_on:
      - db
      - auth
      - landing
