name: dev
on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2

      # Install node dependencies
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
      - run: npm ci --audit=false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run linter
      - name: Linter
        run: npm run lint

  unit:
    needs: linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2

      # Install node dependencies
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
      - run: npm ci --audit=false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run tests
      - name: Tests
        run: npm run test:unit

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit
          path: unit-report/
          retention-days: 30

      # Upload test coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    needs: unit
    permissions:
      packages: read
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci --audit=false
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: run app
      run: npm run serve &
      # todo: ^^ wait until app started

    - name: install browsers
      run: npx playwright install --with-deps

    - name: run tests
      run: npx playwright test

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e
        path: playwright-report/
        retention-days: 30
